// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvnnrcrvcxolvxcghlxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2bm5yY3J2Y3hvbHZ4Y2dobHhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMzEzNTIsImV4cCI6MjA3MDgwNzM1Mn0.vFDLPWNledOGikZYTcGhk88Tqefo_Mb7YC7vu1gBiiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});